# Generated by Django 5.0.6 on 2024-06-18 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Peak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField()),
                ('elevation', models.IntegerField()),
                ('date', models.DateField()),
                ('is_daytime', models.BooleanField()),
                ('temperature', models.IntegerField()),
                ('wind_speed', models.CharField(max_length=20)),
                ('wind_direction', models.CharField(max_length=5)),
                ('precip_chance', models.IntegerField()),
                ('relative_humidity', models.IntegerField()),
                ('description', models.CharField()),
                ('coordinate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='weather.coordinate')),
            ],
            options={
                'ordering': ['coordinate', 'date'],
            },
        ),
    ]
