# Generated by Django 5.0.6 on 2024-06-19 05:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_forecast_date_alter_forecast_precip_chance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coordinate',
            unique_together={('user', 'latitude', 'longitude')},
        ),
    ]
