# Generated by Django 5.0.6 on 2024-06-21 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_coordinate_session_key_alter_coordinate_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='relative_humidity',
            field=models.IntegerField(null=True),
        ),
    ]
