# Generated by Django 5.0.6 on 2024-06-24 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_alter_forecast_relative_humidity'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='uri',
            field=models.URLField(blank=True, null=True),
        ),
    ]
