# Generated by Django 5.0.6 on 2024-06-24 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_forecast_uri'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forecast',
            options={'ordering': ['coordinate', 'generated_at', 'date']},
        ),
        migrations.RenameField(
            model_name='forecast',
            old_name='uri',
            new_name='icon_url',
        ),
    ]
