# Generated by Django 5.0.6 on 2024-10-21 16:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_alter_forecast_options_rename_uri_forecast_icon_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coordinate',
            unique_together={('user', 'session_key', 'latitude', 'longitude')},
        ),
        migrations.AddField(
            model_name='coordinate',
            name='date_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='coordinate',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
