# Generated by Django 5.0.6 on 2025-06-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0008_alter_coordinate_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecast',
            name='relative_humidity',
        ),
        migrations.AddField(
            model_name='forecast',
            name='time_zone',
            field=models.CharField(default='America/Los_Angeles', max_length=40),
        ),
    ]
