# Generated by Django 5.0.6 on 2026-06-09 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0009_remove_forecast_relative_humidity_forecast_time_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='temperature',
            field=models.IntegerField(null=True),
        ),
    ]
